### ISSUE TITLE
Replace cluster symbol 

### ISSUE THREAD

**Issue by mstreit** [jku-vds-lab/projection-space-explorer#111]
Replace black square with dark gray diamond. Maybe a little bit smaller too.

**Comment by mstreit** [comment]
![image](https://user-images.githubusercontent.com/4129755/107335157-df216800-6ab7-11eb-8dd1-dda9e16f5072.png)

**Comment by Aystein** [comment]
diamond shape added, made dark gray, made size 25% smaller
