### ISSUE TITLE
Unify font

### ISSUE THREAD

**Issue by mstreit** [jku-vds-lab/projection-space-explorer#113]
Some parts of the UI show serif, other parts non-serif fonts. Everything should be non-serif.

![image](https://user-images.githubusercontent.com/4129755/107335310-11cb6080-6ab8-11eb-9ecf-2f2d4f5a31b7.png)

LineUp:
![image](https://user-images.githubusercontent.com/4129755/107335372-2576c700-6ab8-11eb-9f8c-6e3c72899f16.png)

**Comment by mstreit** [comment]
@Aystein any change that this will be fixed soon? Thanks!

**Comment by einbandi** [comment]
The font in the VDS Logo SVG is also not correct: 

![grafik](https://user-images.githubusercontent.com/11440522/111181548-6332a800-85ae-11eb-8238-b84a885405ac.png)

**There are three options to fix this:**

1. Use `vds-lab-logo-opt.svg`, which has the text converted into svg paths (optimized version with no inkscape clutter).
2. Use either of the PNG versions `vds-lab-logo-transparent.png` or `vds-lab-logo-whitebg.png`
3. Use the current version, but make sure that [Montserrat Semi-Bold (600)](https://fonts.google.com/specimen/Montserrat?preview.text_type=custom) is used for the "Visual Data Science Lab" text.

All files can be found [here]([here](https://drive.google.com/drive/folders/1hm61i3wOFu7Fwc3TG_DsFc0e4NjkVaFF)).

**Comment by ginihumer** [comment]
I already fixed the font for lineup

**Comment by Aystein** [comment]
I think this issue is resolved now, Lineup uses non-serif, the logo has no text anymore, and material ui also uses non-serif

**Comment by mstreit** [comment]
Looks perfect, thanks
