### ISSUE TITLE
TODOs from bayer

### ISSUE THREAD

**Issue by ginihumer** [jku-vds-lab/projection-space-explorer#115]
- automatisch "colorby" auf "clusterlabel", wenn man clustered
- highlight coresponding points when hovering over cluster name (in the cluster tab)
- jaccard distance (bzw user input zum auswählen einer distance metric) -> sollte für alle embedding methoden funktionieren
- cluster renaming
- loading screen during "preparation" time of embedding -> it takes a while until the updates are shown in the scatter plot. until it starts, there should be a loading message.
- disable normalize checkboxes when feature is not used for projection

**Comment by Aystein** [comment]
- disable normalize checkboxes when feature is not used -> solved
- cluster renaming -> solved
