### ISSUE TITLE
No cluster selection from sidebar when panning tool is active

### ISSUE THREAD

**Issue by keckelt** [jku-vds-lab/projection-space-explorer#117]
Hi,

If I have the Panning Tool active selecting a cluster in the sidebar is not possible:
![image](https://user-images.githubusercontent.com/10337788/107614999-afa36480-6c4b-11eb-9d92-6c89a9e6cb64.png)

It works after i switch to eiher Lasso Select or Cluster tool.

**Comment by keckelt** [comment]
Also, the cluster selection state (color) changes when i switch from the cluster tool to the lasso selection:
![cluster selection state](https://user-images.githubusercontent.com/10337788/107615555-b2528980-6c4c-11eb-9c25-b637f2a37cb4.gif)

**Comment by Aystein** [comment]
cluster selection is reworked
