### ISSUE TITLE
FeatureType is undefined for datasets with arbitrary column headers

### ISSUE THREAD

**Issue by CursedSeraphim** [jku-vds-lab/projection-space-explorer#121]
When loading the penguins dataset the summary visualization table for coral / arbitrary data is displayed, but it remains completely empty, i.e., no histograms or boxplots are drawn.

**Comment by Aystein** [comment]
@CursedSeraphim The issue is related to "featureType" being undefined for this dataset

**Comment by CursedSeraphim** [comment]
intermediate hotfix was pushed with c4c594d5eceba0c3a6c205ec12c3bdb12fae6501 by modifying the header
but a general fix is still necessary such that arbitrary datasets have a featureType

**Comment by CursedSeraphim** [comment]
fixed in ddac90714d83f4ed6c2ad28f545d9bee86180421 by adding default feature labels for columns in the CSVLoader whenever they don't have custom JSON strings in the column headers

@Aystein please confirm that it is also working for you. if so, this can be closed
