### ISSUE TITLE
Update icons (Dataset and LineUp)

### ISSUE THREAD

**Issue by einbandi** [jku-vds-lab/projection-space-explorer#122]
Update the icons for the Dataset and LineUp tabs. Also use the new and slightly refined SVGs for all other tabs. The icons can be found in the attached zip folder.
[icons-20210315.zip](https://github.com/jku-vds-lab/projection-space-explorer/files/6142618/icons-20210315.zip)

**Comment by Aystein** [comment]
updated the icons
