### ISSUE TITLE
Additional minor layout refinements

### ISSUE THREAD

**Issue by einbandi** [jku-vds-lab/projection-space-explorer#124]
I think the following changes would make the interface slightly cleaner:

1. Use whole width for title bar
2. Change logo to no-text version (see issue #113)
3. Add line separators between tab icons and/or increase vertical spacing

Additionally, links to the GitHub page and the paper page might be helpful.

Here's a mockup of all these changes:
![pse-screen-new](https://user-images.githubusercontent.com/11440522/111185335-2668b000-85b2-11eb-8fe2-ce840613737f.png)

**Comment by Aystein** [comment]
Number 2 and 3 make sense, using the whole width for the title bar will waste space in the left/right tab, and also other tools like the "molstar viewer" dont do this (i guess for the same reasons)

**Comment by Aystein** [comment]
![image](https://user-images.githubusercontent.com/9071970/111314276-879b8c80-8661-11eb-81fc-e557f4fd96e0.png)
