### ISSUE TITLE
Inconsistent Star Visualization - Item to Group

### ISSUE THREAD

**Issue by PatrickAdelberger** [jku-vds-lab/projection-space-explorer#128]
**Dataset** Coral Dataset
## Problem
When selecting a group/cluster the star visualization shows all items in cluster/group.
But selecting items with the lasso shows the star visualization to indicate to which cluster/groups the selected items belong.
 
This is not always the case, selecting one ore more clusters/groups and then directly using the lasso selection for the items does not show the star visualization for the selected items.

GIF:
![PSE_item_star_bug](https://user-images.githubusercontent.com/42137747/111325127-b159b100-866b-11eb-9cdf-e5292cd4546d.gif)

**Comment by Aystein** [comment]
Thanks, I fixed this in my branch, will merge this after the meeting
