### ISSUE TITLE
Switch/Toggle Star Visualization - Item to Group

### ISSUE THREAD

**Issue by PatrickAdelberger** [jku-vds-lab/projection-space-explorer#129]
**Dataset** Coral Dataset
## Problem
When selecting a group/cluster the star visualization shows all items in cluster/group.
But selecting items with the lasso shows the star visualization to indicate to which cluster/groups the selected items belong.
 
The star visualization for the items clutters really fast and is not an information that is need every time, could be an optional visualization

GIF
![PSE_item_star_clutter](https://user-images.githubusercontent.com/42137747/111326268-b53a0300-866c-11eb-9f4f-c3005caeda3e.gif)

## Possible Solution
Add a switch/toggle to the Cluster menu item, similar to the 'Show Items' / 'Show Cluster' switch

**Comment by Aystein** [comment]
Added a select to show/hide this information
