### ISSUE TITLE
Add Cluster Labels in Embedding and Story Telling

### ISSUE THREAD

**Issue by PatrickAdelberger** [jku-vds-lab/projection-space-explorer#132]
It becomes really difficult to keep track of the different cluster, especially if there are no label to keep them apart.

It would improve the usability immensely to just show the labels on hover.

![image](https://user-images.githubusercontent.com/42137747/111357374-89794600-8689-11eb-800e-c3664ebb92e0.png)

**Comment by Aystein** [comment]
I also added this to meeting notes
