### ISSUE TITLE
Story Telling: Show Cluster/Group as Diamond

### ISSUE THREAD

**Issue by PatrickAdelberger** [jku-vds-lab/projection-space-explorer#133]
Currently the clusters/groups are represented as sqaures with their story telling number next to it.

I think it wouls look better if you use the same representation that is used in the embedding: **diamond with number in it**
**Suggestion**
![image](https://user-images.githubusercontent.com/42137747/111358779-0658ef80-868b-11eb-88af-3e07763e50f3.png)

**Comment by Aystein** [comment]
Changed the symbol to a diamond since that makes sense, I made a note for the discussion tomorrow for the label
