### ISSUE TITLE
Story Telling: Missing Attribute in Change Visualization List

### ISSUE THREAD

**Issue by PatrickAdelberger** [jku-vds-lab/projection-space-explorer#134]
**Version**: Develop
**Date**: 16-03-2021 19:15

## Problem

**Dataset:** Coral no one-hot encoding normalized
**Reproduction**
1. Projection with the default attributes.
2. Add connection between cohort 5 and cohort 10
3. Open Story Telling mode for this connection

The **KRAS: AA Mutated** attribute is not in the list of the changes. Even though the threshold is set to the minimum.
**_KRAS: AA Mutated_**: Is a categorical attribute and changes from only having **Mutated** to only having **Non-Mutated** samples, which is big changes and should therefore be in the list of changes.

Screenshot:
![image](https://user-images.githubusercontent.com/42137747/111360852-897b4500-868d-11eb-8873-173467b8a433.png)

**Comment by CursedSeraphim** [comment]
addressed / fixed in a7d9b7dd1f0302b4d25d87ae724451ccae49cef4
please verify and close the issue if it works on your end as well @PatrickAdelberger 

![image](https://user-images.githubusercontent.com/29144639/111984864-36c9df00-8b0c-11eb-81dd-66fab0690b06.png)

**Comment by PatrickAdelberger** [comment]
@CursedSeraphim 
It works, thanks
