### ISSUE TITLE
Cluster position is not updated

### ISSUE THREAD

**Issue by keckelt** [jku-vds-lab/projection-space-explorer#137]
I think the clusters positions are not updated when doing a new projection.
tested on https://develop--projection-path-explorer.netlify.app/

Steps to reproduce:
* Select penguin dataset
* Project the data with UMAP: species as only attribute, 20 neighbors
* You should see 3 distinct clusters soon
* create a group from each cluster
* Project the again with UMAP
  * Attributes: 
    * bill length 
    * bill depth
    * flipper length
    * body mass
  * neighbors: 20

![image](https://user-images.githubusercontent.com/10337788/111618133-4bdd0000-87e4-11eb-8bfd-ae56f259fa77.png)

**Comment by keckelt** [comment]
I tried to change the story book to none and back, to force it to update; but it is still at the same position.

But: the projection was significantly faster without the clusters being shown (~1minute for the first 150 iterations vs a few seconds for iterations 150-500).

**Comment by Aystein** [comment]
Thanks for detecting this, had a typo in last commit.
The speed issue is related to the geometry which is recalculated for the new positions, this will be lazily calculated now
(Will push changes today)
