### ISSUE TITLE
Empty String as Category Label for Categorical Columns with Empty Cells

### ISSUE THREAD

**Issue by PatrickAdelberger** [jku-vds-lab/projection-space-explorer#140]
Version: Develop
Date: 22-03-2021 13:30

## Problem
Dataset: [coral_usecase_no_structure_subsampled_normalized_no_one_hot.zip](https://github.com/jku-vds-lab/projection-space-explorer/files/6182135/coral_usecase_no_structure_subsampled_normalized_no_one_hot.zip)
Reproduction
1. Load the dataset abive
2. Go to the Encodings tab
3. Color by KRAS AA Mutated (categories: 'Mutated', 'Non-Mutated','')

Color coding works, but one label for the Color is empty. This is also the case for the summary. 
The functionality is still given, there is just no text for the category.

GIF
![PSE_empty_category](https://user-images.githubusercontent.com/42137747/111991306-7268a700-8b14-11eb-9523-47ce217fe345.gif)

## Possible Solution
Define a label for such a case: 'null', 'Missing Value', ..
Maybe check also if the label already exists in the column, e.g. column has these categories: 'null','CatA', 'CatB', and ''

**Comment by Aystein** [comment]
For empty strings, the label shown is not '<No Value>'
