### ISSUE TITLE
contour-mode bug

### ISSUE THREAD

**Issue by ginihumer** [jku-vds-lab/projection-space-explorer#149]
when generating groups in "None" mode, the contours won't show when changing to "contour" mode
![image](https://user-images.githubusercontent.com/45741696/112638081-259c0d80-8e3f-11eb-9af5-6f83494d2c35.png)

**Comment by Aystein** [comment]
The expected behavior is that the contour is only shown when the cluster is selected

**Comment by Aystein** [comment]
Resolved
