### ISSUE TITLE
Wrong Square Colors for the Chess Summary/Difference Visualization.

### ISSUE THREAD

**Issue by PatrickAdelberger** [jku-vds-lab/projection-space-explorer#152]
Currently chessboard square's coloring is inverted.

Screenshot:
![image](https://user-images.githubusercontent.com/42137747/112851249-18835680-90ab-11eb-89b7-6ad8905cb699.png)

## Solution: 
Change the light color square to dark color and the dark color square to light color.
The colors (gray, blue, or brown) are not important just that the darker one is in the left bottom corner.

Screenshot:
![image](https://user-images.githubusercontent.com/42137747/112851777-97788f00-90ab-11eb-9123-16267774fdb9.png)

**Comment by CursedSeraphim** [comment]
fixed in badc592c39c1e6764db44dcd0e8dbae27251bdfd

if this change works on your end, this issue can be closed

![chess colour invert](https://user-images.githubusercontent.com/29144639/112945248-54aec980-9134-11eb-9c48-153957c1fdee.PNG)

**Comment by PatrickAdelberger** [comment]
Works, too :+1: 
Thanks
