### ISSUE TITLE
Change Label from `Fingerprint Attributes` to `Summary Attributes`

### ISSUE THREAD

**Issue by PatrickAdelberger** [jku-vds-lab/projection-space-explorer#153]
The button in the Details menu is currently labeled **Fingerprint Attributes**. Should be changed to **Summary Attributes**

Screenshot:
![image](https://user-images.githubusercontent.com/42137747/112852199-fdfdad00-90ab-11eb-80cf-81a40e619ff6.png)

**Comment by CursedSeraphim** [comment]
fixed in badc592c39c1e6764db44dcd0e8dbae27251bdfd

if this change works on your end this issue can be closed

![Summary Attributes](https://user-images.githubusercontent.com/29144639/112945161-3517a100-9134-11eb-8ffe-3b98311cc13d.PNG)

**Comment by PatrickAdelberger** [comment]
Works :+1: 
Thanks
