### ISSUE TITLE
Change Chess Styling

### ISSUE THREAD

**Issue by einbandi** [jku-vds-lab/projection-space-explorer#154]
- Use new icons (attached; naming scheme should be the same as previously used)
- Change dark chessboard color to light blue (`bee1ef`)
- Change light chessboard color to white (`ffffff`)
- Introduce light blue (`bee1ef`) border with a width of 1/10 of the width of one field
- Change difference encoding: color field with "strongest" difference orange (`ff9900`); encode weaker differences with decreasing opacity (**not** by increasing brightness, because then equal fields would all end up white; equal blue fields should still be blue)

[new_chess_icons.zip](https://github.com/jku-vds-lab/projection-space-explorer/files/6227642/new_chess_icons.zip)

**Comment by einbandi** [comment]
I assigned medium priority because it would be nice to have already for the paper screenshots

**Comment by CursedSeraphim** [comment]
addressed in multiple individual commits
91da3e3fd0703d8f1c5bde9ac2ddc3b84398bc06
46ed6fbab6600de402be2521de946ab09121dba7
367c80aff8b2904893bc0bbd2397ab38c6c85ecc
e6728ec0f672d8fd185b8c261202d9ef3be0e2c1
4f0ed37ed197be82bac01ee19021ea055c2f6173

please check whether this is the expected behaviour and close the issue if that is the case and everything works

![image](https://user-images.githubusercontent.com/29144639/112980265-f268bf80-9159-11eb-8dc5-6ef5884eaf6f.png)


![image](https://user-images.githubusercontent.com/29144639/112980250-ebda4800-9159-11eb-99b5-62ef48ce9b42.png)

**Comment by CursedSeraphim** [comment]
using opacities from selection A for colours differences:

88903da03d96b2097ebc89c76b1661e0ab1011fe

![image](https://user-images.githubusercontent.com/29144639/112985256-3f4f9480-9160-11eb-9e20-3a8ef9f0448c.png)

![image](https://user-images.githubusercontent.com/29144639/112985266-44acdf00-9160-11eb-9b15-c6f8da49e43a.png)

**Comment by einbandi** [comment]
Can you please change the color of the dark chess fields (and the border) to `edeeef` and the color of the highest difference to `007dad`? Then encode the difference in the brightness, using fully opaque colors. The brightest field (i.e. smallest difference) should have a brightness of slightly less then 100% (mabye 90%). This will avoid the issue of dark fields appearing white when there is little change. Here's an image that shows the darkest and brightes difference encoding on top of dark and white fields.

![grafik](https://user-images.githubusercontent.com/11440522/112992011-1206e480-9168-11eb-941d-cf7ebc5f7d58.png)

**Comment by CursedSeraphim** [comment]
implemented with a1d235f427286beed555dc995930d23d655815b8

![image](https://user-images.githubusercontent.com/29144639/112994163-42e81900-916a-11eb-8273-ae6be99b44b1.png)

**Comment by PatrickAdelberger** [comment]
Works, thanks :+1:

**Comment by PatrickAdelberger** [comment]
The chessboards are blue and white again, and the changes orange.
@CursedSeraphim could you look into it please, I guess somewhere the changes got lost during a merging process.

**Comment by CursedSeraphim** [comment]
yes I think some old bundles were merged somewhere
I let the bundles recompile on my end to where the grey/blue chess code took effect again and pushed with commit c577d7fde41b86227235600d2bdfda195e9c27b5
