### ISSUE TITLE
Only one contour polygon drawn per contour level

### ISSUE THREAD

**Issue by einbandi** [jku-vds-lab/projection-space-explorer#172]
For each contour level only one polygon is drawn, even when the resulting density at that level is multimodal.

Example:
![grafik](https://user-images.githubusercontent.com/11440522/128886892-5fa1b969-085b-4079-a08b-e1461a45aacf.png)

Note that [`d3.contourDensity`](https://github.com/d3/d3-contour#contourDensity) returns an array of  [GeoJSON `MultiPolygon`](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.7) objects, where each `MultiPolygon`'s `coordinate` member holds an array of coordinate arrays. I think the cause of the error is [here](https://github.com/jku-vds-lab/projection-space-explorer/blob/master/src/components/WebGLView/Visualizations/MultivariateClustering.tsx#L528), where only the first of the coordinate arrays is iterated over.

**Comment by einbandi** [comment]
I thought this was already fixed somewhere because we discussed this issue several months ago, but I couldn't find any issue and the Slack posts can no longer be accessed.

**Comment by PatrickAdelberger** [comment]
> I think the cause of the error is [here](https://github.com/jku-vds-lab/projection-space-explorer/blob/master/src/components/WebGLView/Visualizations/MultivariateClustering.tsx?rgh-link-date=2021-08-10T14%3A40%3A20Z#L528), where only the first of the coordinate arrays is iterated over.

Yes, there should be an additional loop over the coordinates ([example](https://observablehq.com/@d3/density-contours))
```tsx
let contours = d3.contourDensity()
                    .x(d => xAxis(d.x))
                    .y(d => yAxis(d.y))
                    .bandwidth(10)
                    .thresholds(10)
                    .size([100, bounds.width == 0 ? 1 : Math.floor(100 * (bounds.height / bounds.width))])
                    (cluster.vectors.map(vect => ({ x: vect.x, y: vect.y })))

let clusterObject = this.clusterObjects.find(e => e.cluster.label == cluster.label)

let material = new THREE.LineBasicMaterial({ color: clusterObject.lineColor.hex })

const points = []
contours.forEach(contour => {
			contour.coordinates.forEach( polygon => {    	 
			const coordinates = polygon[0]

		    for (let i = 0; i < coordinates.length - 1; i++) {
		        let cur = coordinates[i]
		        let next = coordinates[i + 1]
		    
		        points.push(new THREE.Vector3(xAxis.invert(cur[0]), yAxis.invert(cur[1]), -5))
		        points.push(new THREE.Vector3(xAxis.invert(next[0]), yAxis.invert(next[1]), -5))
		    }
	}
})
let line = new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(points), material)
```

**Comment by keckelt** [comment]
I made a change to the https://github.com/jku-vds-lab/projection-space-explorer/tree/structure branch that likely resolved the issue.

**Comment by PatrickAdelberger** [comment]
> I made a change to the [`structure`](https://github.com/jku-vds-lab/projection-space-explorer/tree/structure) branch that likely resolved the issue.

Yes, it works for me! :tada:
