### ISSUE TITLE
Clustering does no longer work

### ISSUE THREAD

**Issue by keckelt** [jku-vds-lab/projection-space-explorer#183]
Hi,

Clustering no longer works when PSE is not deployed on AWS:
![image](https://user-images.githubusercontent.com/10337788/149466795-355ddb2c-1957-4d5a-85c6-97c90b648ef1.png)

It tries to load/send data from AWS and that fails because its a Cross Origin Request. 
URL in Code: https://github.com/jku-vds-lab/projection-space-explorer/blob/master/src/utils/backend-connect.ts#L6

**Comment by ginihumer** [comment]
cime.caleydoapp.org task was down on AWS
