### ISSUE TITLE
split featureType enum for dataset into featureType + dataType

### ISSUE THREAD

**Issue by CursedSeraphim** [jku-vds-lab/projection-space-explorer#91]
would be better if the featureType only differentiated between categorical / quantitative, with an additional field dataType integer/float/date/etc such that all further decisions can be based on a combination of featureType+dataType

e.g., use date vega spec if quantitative + date, let user decide between categorical / quantitative if dataType is integer

**Comment by Aystein** [comment]
I think this is no longer necessary
