### ISSUE TITLE
Display cluster labels and edge labels

### ISSUE THREAD

**Issue by CursedSeraphim** [jku-vds-lab/projection-space-explorer#93]
projection  + cohorts would read better if the cluster labels and edge labels were displayed in the projection

e.g.:
![image](https://user-images.githubusercontent.com/29144639/97799063-b9203800-1c2b-11eb-9bbf-d20409f24cb4.png)

**Comment by Aystein** [comment]
https://idl.cs.washington.edu/papers/fast-labels/
just posting this here so it does not get lost, might be the best solution

**Comment by CursedSeraphim** [comment]
edge labels are being rendered now

the way centroids should be visualized has been discussed and additional labels might cause unnecessary clutter

can re-open if we decide to add cluster labels as well
